### ISSUE TITLE
Body in GET request

### ISSUE THREAD

**Issue by kag0** [Mashape/unirest-java#105]
I noticed that unirest(and other libraries) don't allow a body for GET requests. The HTTP standard does not forbid bodies for GET, but it seems taboo in practice. Why is this?

**Comment by zodvik** [comment]
Lots of server implementation ignore body in GET requests.

**Comment by kag0** [comment]
I noticed that, but the HTTP standard doesn't give any indication that it's forbidden. Is there a particular reason not to use it or do libraries just not use it in order to be safe with other libraries?
