### ISSUE TITLE
Retry failed requests

### ISSUE THREAD

**Issue by magicgoose** [Mashape/unirest-java#133]
A very useful feature is apparently missing — ability to transparently retry requests, before failing, and configurable number of retries.

**Comment by shashiranjan84** [comment]
You can make custom HttpClient with custom retry logic. Like using DefaultMethodRetryHandler even create cutom Retry handler.

**Comment by brsanthu** [comment]
While we could re-configure httpclient, the whole point of Unirest is easy and consistent abstraction across different languages. So it would be great if unirest provides that abstraction to enable retry.

**Comment by Zuckonit** [comment]
maybe wrapper with guava-retrying is another choice
