### ISSUE TITLE
Curl --data-binary request using Unirest ?

### ISSUE THREAD

**Issue by knightofbatons** [Mashape/unirest-java#163]
Hi I apologize if this question is basic
English is not my mother tongue and my english is very poor not know can give my question clearly
I am using Java and Unirest for Java to query an api to reproduce this curl request. 
`curl -s -i -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' http://<some-ip>:8088/ws/v1/cluster/apps --data-binary @spark-yarn.json`
I think I am stuck on how to get the --data-binary flag using Unirest
I have try 

```
        String urlCreate = "http://<some-ip>:8088/ws/v1/cluster/apps";
        Unirest.post(urlCreate)
                .header("Accept","application/json")
                .header("Content-Type","application/json")
                .body(<some-jsonData>).asBinary() 
```

but it does not work
before that I use`.body(<some-jsonData>).asJson()` as Curl --data/-d it works well
Please help

**Comment by knightofbatons** [comment]
I have sloved my question by
read your unit testing
UnirestTest.java thankyou

**Comment by ELMASTAS** [comment]
ok
no  problems  ı cant  help  you


2016-08-19 12:35 GMT+03:00 knightofbatons <notifications@github.com>:

**Comment by ELMASTAS** [comment]
https://apps.twitter.com/ ----------------------------------->you can make
twitter apı
or custumer  key here use twintter apı

2016-08-20 19:46 GMT+03:00 mehmet sabri elmastaş <sabri.elmastas@gmail.com>:
