### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/nio/reactor/IOReactorException

### ISSUE THREAD

**Issue by CoughDropDev** [Mashape/unirest-java#167]
I'm having a problem with me getting an error every time I try and do Unirest.get(url).asJson();. The weird part about it though is that it works fine in eclipse but when I have it built and run it independently I get this exception error(and yes the class file is there).

**Comment by CoughDropDev** [comment]
I am also not the only 1 with this exact same problem, as I'm making a forge mod with this as well http://stackoverflow.com/questions/36659980/java-jar-classnotfoundexception-even-though-dependent-library-exists#

**Comment by CoughDropDev** [comment]
Dead Project

**Comment by poliveira89** [comment]
I have referenced this issue on my own, before I opened mine I did not found yours.
But after putting some thought on this, I was looking for traces of activity or inactivity on this repository and came across yours.

Did you solve it? Changed to an alternative? 
Best regards.
