### ISSUE TITLE
[Request] Set a proxy

### ISSUE THREAD

**Issue by jamesst20** [Mashape/unirest-java#57]
Hi,

I would like to be able to sniff using Fiddler some outgoing http/https request but I am unable to setup a proxy using Unirest.

Could you please make this feature?

Thanks

**Comment by kimoi** [comment]
Also interested in this.

**Comment by thefosk** [comment]
I've implemented this functionality and it's available in version `1.3.28` using the `Unirest.setProxy()` method. I'm going to close this issue now.

**Comment by faisalbasra** [comment]
Does it support Https?
