### ISSUE TITLE
timeouts ignored for Async calls

### ISSUE THREAD

**Issue by naory** [Mashape/unirest-java#62]
When testing with the Synchronous API and testing my timeouts I can see both:

	SocketTimeoutException: connect timed out
	
and 

	SocketTimeoutException: Read timed out
	
however, when trying the Async calls timeouts are completely ignored

**Comment by thefosk** [comment]
@naory could this be related to #64 ?

**Comment by thefosk** [comment]
@naory can you please try again with the latest version?

**Comment by naory** [comment]
thanks @thefosk, I will look to retest with the latest version.

**Comment by naory** [comment]
the issue was on version 1.3.27. 
I retested with 1.4.5. and it is working fine.
