### ISSUE TITLE
Proxy for fiddler

### ISSUE THREAD

**Issue by jakon89** [Mashape/unirest-java#65]
HI,
Can I set proxy for each request?
I want to set up fiddler with my app where I use unirest library.
Does Unirest support proxy config?
I set:
```java
 System.setProperty("http.proxyHost", "127.0.0.1");
        System.setProperty("https.proxyHost", "127.0.0.1");
        System.setProperty("http.proxyPort", "8888");
        System.setProperty("https.proxyPort", "8888");
```
but it doesn't works. I still can't see traffic form my app.

Thanks for providing great http library for java :)

**Comment by thefosk** [comment]
I've implemented this functionality and it's available in version `1.3.28` using the `Unirest.setProxy()` method. I'm going to close this issue now.
