### ISSUE TITLE
Store HTTP header names in lower case

### ISSUE THREAD

**Issue by spootze** [Mashape/unirest-java#67]
As per http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2, message headers should be case insensitive. Example: using HttpRequest.header("User-Agent",...) results in both "User-Agent" with a custom value and "user-agent" with a default value present in a request. Storing headers names in lower case solves this.

**Comment by sachinwalia2k8** [comment]
One solution would be to use Apache Commons Collections Case Insensitive Map for storing headers. However that'd increase the dependency footprint. In any case here is a link:

https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/CaseInsensitiveMap.html

**Comment by feribg** [comment]
This is a real problem for me too, different APIs return different cases for the headers. Something like that should work:

```
public class CaseInsensitiveMap extends HashMap<String, String> {

    @Override
    public String put(String key, String value) {
       return super.put(key.toLowerCase(), value);
    }

   public String get(String key) {
       return super.get(key.toLowerCase());
    }
}
```

**Comment by thefosk** [comment]
I think a cleaner solution is to use

```java
Map<String, List<String>> headers = new TreeMap<String, List<String>>(String.CASE_INSENSITIVE_ORDER);
```

**Comment by feribg** [comment]
Yep gets the job done either way, headers are few enough so the perf difference between tree and hash map is irrelevant. Thanks for the fix.
