### ISSUE TITLE
Headers transformed to LowerCase?

### ISSUE THREAD

**Issue by shuron** [Mashape/unirest-java#73]
According to HTTP Spec Headers begins with Capital letters. For Expample "Location".
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30
That is also what server retreives. 

But using 
response.getHeaders().get("Location"); retreives null
response.getHeaders().get("location"); retreives Headers... 

So why are the LowerCase? Think this must be more strickt to HTTPStandard...

**Comment by karmakaze** [comment]
For certain, the implementation of response.getHeaders().get("Location") should take the key and also map it to lowercase as it did while reading the stream. This is a 'huge' *bug*.

**Comment by thefosk** [comment]
@shuron @karmakaze what version of Unirest are you using? This should have been fixed in one of the latest releases

**Comment by karmakaze** [comment]
Hi Marco,

I'm using version 1.4.5 from maven repos.

Cheers,
- Keith

**Comment by shashiranjan84** [comment]
fixed with version 1.4.8

**Comment by jdbevan** [comment]
I'm REALLY confused by this... the RFC linked to by @shuron is the same RFC linked to in https://github.com/Mashape/unirest-java/issues/67 and that RFC states [very clearly](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) that:

> HTTP header fields, which include general-header (section 4.5), request-header (section 5.3), response-header (section 6.2), and entity-header (section 7.1) fields, follow the same generic format as that given in Section 3.1 of RFC 822 [9]. Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

However, according to https://github.com/Mashape/unirest-java/commit/3e4feae0970f050fa19be8f3c9731b63f93a085f the HttpRequest uses case-insensitive headers (but does not, notably, use the Unirest Headers object) and according to https://github.com/Bludwarf/unirest-java/commit/b60fa785f2404134c760ccb27a968a532374fed0 the HttpResponse uses case-sensitive headers.

This is inconsistent at best, and really quite confusing... can anyone shed some light on why this inconsistency exists?

In my opinion ALL headers should be stored using the Unirest Headers object, and that should provide a case-insensitive method of both storing and retrieving headers...
