### ISSUE TITLE
should support any HTTP method

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/unirest-java#77]
having utility class methods/functions is nice, but there should be a generic way to make an API call passing in a string for HTTP Method.

cc: @shashiranjan84

**Comment by SGrondin** [comment]
@shashiranjan84 is working on it.

**Comment by montanaflynn** [comment]
@shashiranjan84 has issued a PR: https://github.com/Mashape/unirest-java/pull/78 but it's failing a test
