### ISSUE TITLE
Can't get my build to use the unirest-java-version of org-apache.http.client instead of the one shipped with Android (I'm at API 16)

### ISSUE THREAD

**Issue by drblue** [Mashape/unirest-java#81]
Hi,

I'm having trouble with unirest-java on API level 16. I have compiled a JAR `unirest-java-1.4.6-SNAPSHOT-withDependency-ShadedForAndroid` with all dependencies and also some Apache-libs shaded - but I'm still getting errors about my app not finding `org.apache.http.client.methods.HttpRequestBase.releaseConnection`. Which I have concluded is due to it using the built-in apache-libs instead of the ones I compiled in with the unirest-JAR.

LogCat:
[http://pastebin.com/5MCSa7eg]

unirest-java/pom.xml:
[http://pastebin.com/ThHZn3sN]

**Comment by shashiranjan84** [comment]
Please follow the link http://blog.mashape.com/using-unirest-java-for-your-android-projects/
